### ISSUE TITLE
Wrong data-* set cause endpoint not set error

### ISSUE THREAD

**Issue by slabbdev** [cors-gmbh/friendly-captcha-bundle#2]
https://github.com/cors-gmbh/friendly-captcha-bundle/blob/5a9e1264b526137215bb4c6ae164fa6645ceb8e1/src/Form/Type/FriendlyCaptchaType.php#L32

result to `<div data-puzzle-puzzle-endpoint="XXX">`

everything's ok when replace #L32 by:
`'puzzle-endpoint' => $this->endpoint,`

**Comment by elernonelma** [comment]
To anyone attending this patch, we created a fork of this repository to maintain it https://github.com/Elma/friendly-captcha-bundle.

**Comment by breakone** [comment]
Sorry for the late response. Is fixed in [Release 1.0.2.](https://github.com/cors-gmbh/friendly-captcha-bundle/tree/v1.0.2)
