### ISSUE TITLE
Template declaration missing ?!

### ISSUE THREAD

**Issue by slabbdev** [cors-gmbh/friendly-captcha-bundle#5]
Not an issue but simple proposal.
Maybe it could be a good thing to add templates declaration to a compiler as we got here:

https://github.com/Elma/friendly-captcha-bundle/blob/2088676e6ec264eeea32065a8334f44989a8cf45/src/DependencyInjection/Compiler/ResourceCompilerPass.php

**Comment by dpfaffenbauer** [comment]
Honestly, I don't like these kinds of things, either add it to a twig config, or add it in the template. Not necessary to force the developer to certain things he cannot change.
