### ISSUE TITLE
Can't get frc-captcha-solution data in validator

### ISSUE THREAD

**Issue by barbieswimcrew** [cors-gmbh/friendly-captcha-bundle#6]
Hey there, thanks for your bundle. While trying to integrate it to my contact form I've some issues with the validation... 

```
$builder->add('captcha', FriendlyCaptchaType::class, options: [
                'lang' => 'de',
                'start' => 'auto',
                'constraints' => [
                    new FriendlyCaptchaValid()
                ]
            ]); 
```

Tried to add the constraint like shown above. But when it comes to the form submit the `FriendlyCaptchaValidValidator` crashes due to there is no value and thus the http request to the API returns status 400.

As there is no further documentation on how to do right, I actually have no clue what I'm doing wrong here. Hopefully you can help? Thanks in advance and kind regards!

**Comment by dpfaffenbauer** [comment]
@barbieswimcrew Where does it crash with "no" value?

**Comment by barbieswimcrew** [comment]
Hi @dpfaffenbauer, I have a Symfony UX Live Component (almost like in this example: https://ux.symfony.com/live-component/demos/auto-validating-form). As soon I submit the form, the validation fails in the method $this->submitForm(). If I debug the request, the captcha doesn't have a value and so the $value injected to the `FriendlyCaptchaValidValidator` is empty as well. This means the http request your validator executes against the friendlycaptcha API will throw an exception because of the returned status code. Guess that's totally fine because the value is empty... but I have no idea why it is empty at all... I'm not sure if I'm missing something but as far as I can see your bundle doesn't provide any further examples on how to use it so maybe I'm doing something wrong..?!

**Comment by dpfaffenbauer** [comment]
OK, honestly: no idea, we don't use Symfony UX yet, so we don't run into that issue. Maybe you can further debug and find out the problem.

**Comment by barbieswimcrew** [comment]
I really don't want to bother you or waste your precious time but might you have an example on how you use your bundle? As I wrote before.... maybe I missed something. I added the field to the form type:

```
->add('captcha', FriendlyCaptchaType::class, options: [
                'lang' => 'de',
                'start' => 'auto',
                'constraints' => [
                    new FriendlyCaptchaValid()
                ]
            ])
```
And of course I rendered it in the TWIG template like so:
```
{{ form_row(form.captcha) }}
```
To get the rendering correct, I had to copy the template out of your package to my theme:
```
{%- block cors_friendly_catcha_type_row -%}
    <div class="frc-captcha"
         data-sitekey="{{ form.vars.sitekey }}"
         data-solution-field-name="{{ form.vars.full_name }}"
            {% for type, value in form.vars.friendly_captcha %}
                data-{{ type }}="{{ value }}"
            {% endfor %}
    >
    </div>
{%- endblock cors_friendly_catcha_type_row -%}
```
I had to add the JS script to get the field then rendered properly in the frontend. 

Well... I have no clue... 🙅

**Comment by dpfaffenbauer** [comment]
We use it like this:

```php
//Form Type
->add('captcha', FriendlyCaptchaType::class, [
    'constraints' => new FriendlyCaptchaValid()
])
```

```twig
{# twig #}
{{ form_row(form.captcha) }}
```

```js
//Javascript
// Package: "friendly-challenge": "^0.9.8",

import "friendly-challenge/widget";
```

**Comment by barbieswimcrew** [comment]
@dpfaffenbauer thanks for that! I finally got it to work by the help of symfony's ryan weaver. Sorry for the inconvenience!

**Comment by dpfaffenbauer** [comment]
@barbieswimcrew could you maybe share the solution here?

**Comment by barbieswimcrew** [comment]
@dpfaffenbauer With pleasure!  Basically, the Symfony UX Live Component works with a hotwired stimulus controller on the JS side. 

In order for the FriendlyChallenge widget to be loaded at all and to be re-rendered after the asynchronous form submit, you first have to extend the stimulus controller, register to the `render:finished` hook and use `widget.reset()` to reload the widget. I had that basically right before!

The problem lay here: The widget fills a hidden field with a token. However, this token was not included in the request when the form was submitted. The reason for this was that the live component did not notice that the value of the hidden field had changed. To solve this, I had to manually dispatch the `change` event inside the widget instances `doneCallback` method. 

Let me show you my controller code below:

```
'use strict';

import {getComponent} from '@symfony/ux-live-component';
import {Controller} from "@hotwired/stimulus";
import {WidgetInstance} from "friendly-challenge";

/* stimulusFetch: 'lazy' */
export default class ContactFormController extends Controller {
    async initialize() {
        this.component = await getComponent(this.element).then((component) => {
            const widget = new WidgetInstance(document.querySelector('.frc-captcha'), {
                doneCallback: () => {
                    const captchaField = document.querySelector('[name="type[captcha]"]');
                    captchaField.dispatchEvent(new Event('change', {bubbles: true}));
                }
            });

            component.on('render:finished', (component) => {
                widget.reset();
            });
        });
    }
}
``` 

So the `captchaField.dispatchEvent(new Event('change', {bubbles: true}));` finally did the trick!

Hope this was understandable and that it helps others in the future who have similar problems as me. :-)

**Comment by dpfaffenbauer** [comment]
@barbieswimcrew wonderful, many thanks 🍻
